-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAbDoFfqbFc9ABLMQ
nLjBeJXxFqd+vUHKw6wV0QOoj7GgCgYIKoZIzj0DAQehRANCAAS48wC4nCN/ezLX
P2phgkjMOYXhqoum/FSBAmQttbXmD1w1Sevs6miG6VQitK8AsxnupFCBU0qGOSK/
zF7BAMMH
-----END PRIVATE KEY-----