module.exports = {
    Modal: require('./Modal'),
    Heading: require('./Heading'),
    Code: require('./Code'),
    Alert: require('./Alert'),
    Button: require('./Button'),
    ButtonGroup: require('./ButtonGroup'),
    Link: require('./Link'),
    QRScanner: require('./QRScanner'),
    Text: require('./Text'),
    TextInput: require('./TextInput'),
    Select: require('./Select'),
    DatePicker: require('./DatePicker'),
    DateRangePicker: require('./DateRangePicker'),
    EntityFilter: require('./EntityFilter'),
    Icon: require('./Icon'),
    ToggleView: require('./ToggleView'),
    Audio: require('./Audio'),
    AudioRecorder: require('./AudioRecorder'),
    AudioInput: require('./AudioInput'),
    ImageInput: require('./ImageInput'),
    DocumentInput: require('./DocumentInput'),
    QRCodeInput: require('./QRCodeInput'),
    DateInput: require('./DateInput'),
    VideoInput: require('./VideoInput'),
}
